### ISSUE TITLE
Add pipelines

### ISSUE THREAD

**Issue by fiftin** [ansiphore/ansiphore#7]
Pipeline config prototype:

```yaml
repository: deploy
key: test



task_templates:
  build:
    type: build
    playbook: build
    inventory: localhost
    environment: empty


  deploy_to_dev:
    type: deploy
    build_task_template: build


tasks:
- build
- deploy_to_dev
- deploy_to_prod:
    requires:
    - deploy_to_dev
```
